export const HEADER_INTERNAL = [
  { width: '50px', title: 'COMMON.NO', field: 'indexNo' },
  { width: '150px', title: 'PURCHASE_ORDER.PR_NO', field: 'prNo' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.ITEM_CODE', field: 'itemCode' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.PART_NO', field: 'partNo' },
  { width: '150px', title: 'PURCHASE_ORDER.ITEM.ITEM_NAME', field: 'itemName' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.ITEM_TYPE', field: 'itemType' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.UOM', field: 'unit' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.QUANTITY', isRequired: 'true', field: 'quantity' },
  { width: '150px', title: 'PURCHASE_ORDER.ITEM.UNIT_PRICE', field: 'price' },
  { width: '150px', title: 'PURCHASE_ORDER.ITEM.INTO_MONEY', field: 'intoMoney' },
  { width: '200px', title: 'PURCHASE_ORDER.ITEM.EXPECTED_DATE', isRequired: 'true', field: 'expectedDate' },
  { width: '200px', title: 'PURCHASE_ORDER.ITEM.EXPECTED_RETURN_DATE', isRequired: 'true', field: 'responseDate' },
  { width: '200px', title: 'PURCHASE_ORDER.ITEM.TAX', isRequired: 'true', field: 'tax' },
  { width: '200px', title: 'PURCHASE_ORDER.ITEM.TAX_AMOUNT', field: 'taxAmount' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.PRODUCER_NAME', field: 'producerName' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.GUARANTEE', isRequired: 'true', field: 'guarantee' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.DELIVERY_LOCATION', field: 'deliveryLocation' },
  { width: '200px', title: 'PURCHASE_ORDER.ITEM.TERM_ACCOUNT', field: 'termAccount' },
  { width: '200px', title: 'PURCHASE_ORDER.ITEM.PROJECT_MILESTONE', field: 'projectMilestone' },
  { width: '150px', title: 'COMMON.NOTE', field: 'note' }
];

export const HEADER_EXTERNAL = [
  { width: '50px', title: 'COMMON.NO', field: 'indexNo' },
  { width: '150px', title: 'PURCHASE_ORDER.PR_NO', field: 'prNo' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.ITEM_CODE', field: 'itemCode' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.PART_NO', field: 'partNo' },
  { width: '150px', title: 'PURCHASE_ORDER.ITEM.ITEM_NAME', field: 'itemName' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.ITEM_TYPE', field: 'itemType' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.UOM', field: 'unit' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.QUANTITY', isRequired: 'true', field: 'quantity' },
  { width: '150px', title: 'PURCHASE_ORDER.ITEM.UNIT_PRICE', field: 'price' },
  { width: '150px', title: 'PURCHASE_ORDER.ITEM.INTO_MONEY', field: 'intoMoney' },
  { width: '200px', title: 'PURCHASE_ORDER.ITEM.EXPECTED_DATE', isRequired: 'true', field: 'expectedDate' },
  { width: '200px', title: 'PURCHASE_ORDER.ITEM.EXPECTED_RETURN_DATE', isRequired: 'true', field: 'responseDate' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.PRODUCER_NAME', field: 'producerName' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.GUARANTEE', isRequired: 'true', field: 'guarantee' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.IMPORT_LICENSE', field: 'hasImportLicense' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.CONFORMITY', field: 'isConformity' },
  { width: '100px', title: 'PURCHASE_ORDER.ITEM.ENERGY_EFFICIENCY', field: 'hasEnergyEfficiency' },
  { width: '200px', title: 'PURCHASE_ORDER.ITEM.ORIGIN', field: 'itemOrigin' },
  { width: '200px', title: 'PURCHASE_ORDER.ITEM.TERM_ACCOUNT', field: 'termAccount' },
  { width: '200px', title: 'PURCHASE_ORDER.ITEM.PROJECT_MILESTONE', field: 'projectMilestone' },
  { width: '150px', title: 'COMMON.NOTE', field: 'note' }
];
